// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eBooks.API.Data;

#nullable disable

namespace eBooks.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240626142710_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eBooks.API.Entities.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Liked")
                        .HasColumnType("bit");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Harper Lee",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A classic novel depicting racial injustice in the American South.",
                            Genre = "Fiction,Classic",
                            PublicationYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A dystopian novel portraying a totalitarian society.",
                            Genre = "Dystopian,Science Fiction",
                            PublicationYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jane Austen",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A classic novel exploring themes of love, marriage, and social norms.",
                            Genre = "Classic,Romance",
                            PublicationYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 4,
                            Author = "F. Scott Fitzgerald",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A tale of the American Dream, wealth, and love during the Roaring Twenties.",
                            Genre = "Fiction,Classic",
                            PublicationYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Herman Melville",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "The epic tale of Captain Ahab's obsession with the white whale.",
                            Genre = "Fiction,Adventure",
                            PublicationYear = 1851,
                            Title = "Moby-Dick"
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.R.R. Tolkien",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "An epic fantasy saga about the quest to destroy the One Ring.",
                            Genre = "Fantasy,Adventure",
                            PublicationYear = 1954,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 7,
                            Author = "J.D. Salinger",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A classic coming-of-age novel following Holden Caulfield's journey.",
                            Genre = "Fiction,Coming-of-age",
                            PublicationYear = 1951,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.R.R. Tolkien",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "The prequel to The Lord of the Rings, following Bilbo Baggins' journey.",
                            Genre = "Fantasy,Adventure",
                            PublicationYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Gabriel Garcia Marquez",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A multi-generational saga of the Buendía family in the fictional town of Macondo.",
                            Genre = "Magical Realism,Literary Fiction",
                            PublicationYear = 1967,
                            Title = "One Hundred Years of Solitude"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Leo Tolstoy",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A monumental work depicting the events of Russian society during the Napoleonic era.",
                            Genre = "Historical Fiction,Epic",
                            PublicationYear = 1869,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Homer",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "An ancient Greek epic poem recounting Odysseus' ten-year journey home after the Trojan War.",
                            Genre = "Epic,Mythology",
                            PublicationYear = -800,
                            Title = "The Odyssey"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Dante Alighieri",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "An epic poem that follows the journey of the soul through Hell, Purgatory, and Heaven.",
                            Genre = "Epic,Poetry",
                            PublicationYear = 1320,
                            Title = "The Divine Comedy"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Fyodor Dostoevsky",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A complex novel exploring themes of spirituality, morality, and human nature.",
                            Genre = "Classic,Philosophical Fiction",
                            PublicationYear = 1880,
                            Title = "The Brothers Karamazov"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Fyodor Dostoevsky",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A psychological thriller revolving around guilt, conscience, and redemption.",
                            Genre = "Classic,Psychological Fiction",
                            PublicationYear = 1866,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Oscar Wilde",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A novel about a man whose portrait ages while he retains his youth and beauty.",
                            Genre = "Gothic,Philosophical Fiction",
                            PublicationYear = 1890,
                            Title = "The Picture of Dorian Gray"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Aldous Huxley",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A dystopian vision of a future society obsessed with pleasure and conformity.",
                            Genre = "Dystopian,Science Fiction",
                            PublicationYear = 1932,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Alexandre Dumas",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "An adventure novel of revenge, love, and redemption set in the early 19th century.",
                            Genre = "Adventure,Historical Fiction",
                            PublicationYear = 1844,
                            Title = "The Count of Monte Cristo"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Leo Tolstoy",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A tragic love story set against the backdrop of Russian high society.",
                            Genre = "Classic,Romance",
                            PublicationYear = 1877,
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Paulo Coelho",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A philosophical novel about a shepherd boy's journey to find his personal legend.",
                            Genre = "Fiction,Philosophical",
                            PublicationYear = 1988,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Mark Twain",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A satirical novel following Huck Finn's journey down the Mississippi River.",
                            Genre = "Adventure,Satire",
                            PublicationYear = 1884,
                            Title = "The Adventures of Huckleberry Finn"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Homer",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "An ancient Greek epic poem about the Trojan War and the hero Achilles.",
                            Genre = "Epic,Mythology",
                            PublicationYear = -800,
                            Title = "The Iliad"
                        },
                        new
                        {
                            Id = 22,
                            Author = "J.R.R. Tolkien",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A thrilling epic about the quest to destroy the One Ring and save Middle-earth.",
                            Genre = "Fantasy,Adventure",
                            PublicationYear = 1954,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Mary Shelley",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A Gothic novel exploring themes of creation, science, and humanity.",
                            Genre = "Gothic,Science Fiction",
                            PublicationYear = 1818,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Miguel de Cervantes",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A humorous novel about an elderly knight who sets out on a quest to revive chivalry.",
                            Genre = "Classic,Satire",
                            PublicationYear = 1605,
                            Title = "Don Quixote"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Lewis Carroll",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A whimsical tale about a girl who falls down a rabbit hole into a fantastical world.",
                            Genre = "Fantasy,Children's Literature",
                            PublicationYear = 1865,
                            Title = "Alice's Adventures in Wonderland"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Antoine de Saint-Exupéry",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A philosophical novella about a young prince's journey through the universe.",
                            Genre = "Fable,Children's Literature",
                            PublicationYear = 1943,
                            Title = "The Little Prince"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Markus Zusak",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A story of a girl living in Nazi Germany, narrated by Death.",
                            Genre = "Historical Fiction,War",
                            PublicationYear = 2005,
                            Title = "The Book Thief"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Kurt Vonnegut",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "An anti-war novel that mixes science fiction and dark humor.",
                            Genre = "Satire,Science Fiction",
                            PublicationYear = 1969,
                            Title = "Slaughterhouse-Five"
                        },
                        new
                        {
                            Id = 29,
                            Author = "John Steinbeck",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A novel about the plight of migrant workers during the Great Depression.",
                            Genre = "Historical Fiction,Social Commentary",
                            PublicationYear = 1939,
                            Title = "The Grapes of Wrath"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Ray Bradbury",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A dystopian novel depicting a future society where books are banned.",
                            Genre = "Dystopian,Science Fiction",
                            PublicationYear = 1953,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = 31,
                            Author = "William Golding",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A novel about a group of British boys stranded on an uninhabited island.",
                            Genre = "Dystopian,Psychological Fiction",
                            PublicationYear = 1954,
                            Title = "The Lord of the Flies"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Douglas Adams",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A comedic science fiction series about the misadventures of Arthur Dent.",
                            Genre = "Science Fiction,Comedy",
                            PublicationYear = 1979,
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Charles Dickens",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A historical novel set during the French Revolution, exploring themes of sacrifice and resurrection.",
                            Genre = "Historical Fiction,Classic",
                            PublicationYear = 1859,
                            Title = "A Tale of Two Cities"
                        },
                        new
                        {
                            Id = 34,
                            Author = "C.S. Lewis",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A series of fantasy novels set in the magical land of Narnia.",
                            Genre = "Fantasy,Children's Literature",
                            PublicationYear = 1950,
                            Title = "The Chronicles of Narnia"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Margaret Atwood",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A dystopian novel set in a totalitarian society where women are subjugated.",
                            Genre = "Dystopian,Feminist Fiction",
                            PublicationYear = 1985,
                            Title = "The Handmaid's Tale"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Umberto Eco",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A medieval mystery novel set in an Italian monastery.",
                            Genre = "Historical Fiction,Mystery",
                            PublicationYear = 1980,
                            Title = "The Name of the Rose"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Franz Kafka",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A surreal novel exploring themes of guilt, law, and justice.",
                            Genre = "Absurdist Fiction,Existential",
                            PublicationYear = 1925,
                            Title = "The Trial"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Khaled Hosseini",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A novel about friendship, redemption, and the impact of war in Afghanistan.",
                            Genre = "Historical Fiction,Drama",
                            PublicationYear = 2003,
                            Title = "The Kite Runner"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Ken Follett",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "An epic historical novel set in 12th-century England, centered around the construction of a cathedral.",
                            Genre = "Historical Fiction,Adventure",
                            PublicationYear = 1989,
                            Title = "The Pillars of the Earth"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Carlos Ruiz Zafón",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A mystery novel set in post-war Barcelona, revolving around a forgotten book and its author.",
                            Genre = "Mystery,Gothic",
                            PublicationYear = 2001,
                            Title = "The Shadow of the Wind"
                        },
                        new
                        {
                            Id = 41,
                            Author = "Frances Hodgson Burnett",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A classic children's novel about a young girl who discovers a hidden garden.",
                            Genre = "Children's Literature,Classic",
                            PublicationYear = 1911,
                            Title = "The Secret Garden"
                        },
                        new
                        {
                            Id = 42,
                            Author = "Lois Lowry",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A dystopian novel about a society with strict control over emotions and memories.",
                            Genre = "Dystopian,Young Adult",
                            PublicationYear = 1993,
                            Title = "The Giver"
                        },
                        new
                        {
                            Id = 43,
                            Author = "Franz Kafka",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A novella about a man who wakes up one morning transformed into a giant insect.",
                            Genre = "Absurdist Fiction,Existential",
                            PublicationYear = 1915,
                            Title = "The Metamorphosis"
                        },
                        new
                        {
                            Id = 44,
                            Author = "Margaret Mitchell",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A historical novel set during the American Civil War, centered around Scarlett O'Hara.",
                            Genre = "Historical Fiction,Romance",
                            PublicationYear = 1936,
                            Title = "Gone with the Wind"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Kenneth Grahame",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A children's novel about the adventures of anthropomorphic animals.",
                            Genre = "Children's Literature,Fantasy",
                            PublicationYear = 1908,
                            Title = "The Wind in the Willows"
                        },
                        new
                        {
                            Id = 46,
                            Author = "Bram Stoker",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A Gothic horror novel about the vampire Count Dracula's attempt to move to England.",
                            Genre = "Gothic,Horror",
                            PublicationYear = 1897,
                            Title = "Dracula"
                        },
                        new
                        {
                            Id = 47,
                            Author = "Jack London",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "An adventure novel about a domestic dog's life in the wilds of the Yukon.",
                            Genre = "Adventure,Nature",
                            PublicationYear = 1903,
                            Title = "The Call of the Wild"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Stephen King",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A post-apocalyptic horror novel about a deadly pandemic and its aftermath.",
                            Genre = "Horror,Post-Apocalyptic",
                            PublicationYear = 1978,
                            Title = "The Stand"
                        },
                        new
                        {
                            Id = 49,
                            Author = "Alice Walker",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A novel about the life of African-American women in the Southern United States.",
                            Genre = "Fiction,Historical",
                            PublicationYear = 1982,
                            Title = "The Color Purple"
                        },
                        new
                        {
                            Id = 50,
                            Author = "J.R.R. Tolkien",
                            CoverImage = "https://fakeimg.pl/667x1000/cc6600",
                            Description = "A collection of mythopoeic stories about the history of Middle-earth.",
                            Genre = "Fantasy,Mythopoeia",
                            PublicationYear = 1977,
                            Title = "The Silmarillion"
                        });
                });

            modelBuilder.Entity("eBooks.API.Entities.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("eBooks.API.Entities.Comments", b =>
                {
                    b.HasOne("eBooks.API.Entities.Books", "Book")
                        .WithMany("Comments")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("eBooks.API.Entities.Books", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
